export const CREATE_BATTLE_REQUEST = "CREATE_BATTLE_REQUEST";
export const CREATE_BATTLE_SUCCESS = "CREATE_BATTLE_SUCCESS";
export const CREATE_BATTLE_FAILURE = "CREATE_BATTLE_FAILURE";

export const CREATE_NEW_POST_REQUEST = "CREATE_NEW_POST_REQUEST";
export const CREATE_NEW_POST_SUCCESS = "CREATE_NEW_POST_SUCCESS";
export const CREATE_NEW_POST_FAILURE = "CREATE_NEW_POST_FAILURE";